package cn.edu.xmu.presale.mapper;

import cn.edu.xmu.presale.model.po.PresalePo;
import cn.edu.xmu.presale.model.po.PresalePoExample;
import java.util.List;

public interface PresalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int insert(PresalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int insertSelective(PresalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    List<PresalePo> selectByExample(PresalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    PresalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PresalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PresalePo record);
}